### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by uqpen** [guosheng/refinenet#10]
Hi, How can I download your nyudv2 trained model?

**Comment by guosheng** [comment]
Hi, I just uploaded the nyudv2 trained model and the link can be found on the updated main page. This model uses the improved chained pooling with 4 pooling blocks.

**Comment by mingminzhen** [comment]
how can i train the nyudv2 dataset? Could you upload that in the source code?

**Comment by guosheng** [comment]
@mingminzhen you could follow our voc training demo to write your own code for the nyud dataset.
