### ISSUE TITLE
VOC evaluation

### ISSUE THREAD

**Issue by mingminzhen** [guosheng/refinenet#12]
Category result:
class_idx:1, label_vale:0, class_name:background, pixel_acc:0.9825, IoU:0.9559
class_idx:2, label_vale:1, class_name:aeroplane, pixel_acc:0.9599, IoU:0.8874
class_idx:3, label_vale:2, class_name:bicycle, pixel_acc:0.8327, IoU:0.6743
class_idx:4, label_vale:3, class_name:bird, pixel_acc:0.9127, IoU:0.8918
class_idx:5, label_vale:4, class_name:boat, pixel_acc:0.8342, IoU:0.7617
class_idx:6, label_vale:5, class_name:bottle, pixel_acc:0.8693, IoU:0.7760
class_idx:7, label_vale:6, class_name:bus, pixel_acc:0.9496, IoU:0.9330
class_idx:8, label_vale:7, class_name:car, pixel_acc:0.9248, IoU:0.8707
class_idx:9, label_vale:8, class_name:cat, pixel_acc:0.9686, IoU:0.9083
class_idx:10, label_vale:9, class_name:chair, pixel_acc:0.5660, IoU:0.4101
class_idx:11, label_vale:10, class_name:cow, pixel_acc:0.9376, IoU:0.8864
class_idx:12, label_vale:11, class_name:diningtable, pixel_acc:0.7138, IoU:0.6596
class_idx:13, label_vale:12, class_name:dog, pixel_acc:0.9293, IoU:0.8715
class_idx:14, label_vale:13, class_name:horse, pixel_acc:0.9346, IoU:0.8667
class_idx:15, label_vale:14, class_name:motorbike, pixel_acc:0.9223, IoU:0.8625
class_idx:16, label_vale:15, class_name:person, pixel_acc:0.9426, IoU:0.8923
class_idx:17, label_vale:16, class_name:pottedplant, pixel_acc:0.7323, IoU:0.6389
class_idx:18, label_vale:17, class_name:sheep, pixel_acc:0.9348, IoU:0.9076
class_idx:19, label_vale:18, class_name:sofa, pixel_acc:0.6601, IoU:0.5521
class_idx:20, label_vale:19, class_name:train, pixel_acc:0.9322, IoU:0.8820
class_idx:21, label_vale:20, class_name:tvmonitor, pixel_acc:0.8065, IoU:0.7605
class_idx:22, label_vale:255, class_name:void, pixel_acc:0.0000, IoU:0.0000

The result for VOC evaluation is different from that in paper. why?

**Comment by guosheng** [comment]
Did you get this result by evaluating on the voc val set? 
The result in the paper is for the voc test set. You could evaluate using the pascal voc evaluation server. 
We use multi scale evaluation to generate the test set result.

**Comment by mingminzhen** [comment]
ok, i see. i also want to try NYUDV2 dataset. You have provided the Res101 model, but the result in the paper is for Res152. How can get the result in the paper?

**Comment by guosheng** [comment]
You can follow our training demo to train your own model. Our model with ResNet 152 layers will be released in the future.

**Comment by mingminzhen** [comment]
I try the demo_refinenet_test_example_nyud.m to get the NYUDv2 result. How can I compute the pixel accuracy, mean acc, iou as described in paper? Do you give the corresponding code in the repository? I can not find it.

**Comment by guosheng** [comment]
you could refer to our evaluation demo file: demo_refinenet_evaluate_voc.m
