### ISSUE TITLE
run error in demo_refinenet_evaluate_voc.m

### ISSUE THREAD

**Issue by amiltonwong** [guosheng/refinenet#3]
Hi, @guosheng,

Thanks for updating the package, it works now for running "demo_refinenet_test_voc_custom_data.m".
However, I came accross run error in demo_refinenet_evaluate_voc.m. I debug into "[gen_dataset_info.m](https://github.com/guosheng/refinenet/blob/master/main/gen_dataset_info.m)" . The file "my_dataset_info.mat" (../datasets/voc2012_trainval/my_dataset_info.mat) is missing. 
Could you release that file required?

Although it can be generated according to [line](https://github.com/guosheng/refinenet/blob/master/main/gen_dataset_info.m#L15), the program throws error when executing on that line. Here is the error:

```
Error using textscan
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in my_gen_ds_info_voc (line 12)
train_file_names=textscan(fid, '%s');

Error in gen_dataset_info (line 15)
        ds_info=ds_config.gen_ds_info_fn(ds_config);

Error in demo_refinenet_evaluate_voc (line 78)
ds_info=gen_dataset_info(ds_config);
``` 

It seems some voc2012_trainval materials are needed to be placed at ../datasets/ folder. Could you list the steps for doing that?

Thanks~

**Comment by guosheng** [comment]
before running this demo file for evaluation, you need to download the PASCAL VOC 2012 dataset and place it at: ../datasets/voc2012_trainval
thanks for point out, I have updated the comments in the evaluation demo file
