### ISSUE TITLE
gpu option

### ISSUE THREAD

**Issue by amiltonwong** [guosheng/refinenet#5]
Hi, @guosheng ,

In the package, use_gpu option is used as follows:

```
if run_config.use_gpu
	gpu_num=gpuDeviceCount;
	if gpu_num>1
		gpuDevice(run_config.gpu_idx);
    else
        error('no gpu found!');
	end
end
```

It is fine for machine with more than one gpu. However, for machine with only one gpu will fail to pass the snippet above. One quick solution is to modify as: gpu_num>0

**Comment by guosheng** [comment]
Yes, it's a bug. fixed.
