### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by 501177639** [guosheng/refinenet#8]
Hi,
      I find you use ignore label (e.g. 255 in pascal voc)  as a label to train your model. However, when I test your model, I find your result image would not have this ignore label, why?

**Comment by dongzhuoyao** [comment]
255 means that this class will not participate in training(ignore it ),so it also will not appear in your result image.

**Comment by guosheng** [comment]
Thanks @dongzhuoyao , the label value 255 will be ignored when calculating the dense softmax loss during training.

**Comment by 501177639** [comment]
Thanks @dongzhuoyao @guosheng .  I find vl_nnloss will ignore label value 0.  I miss it before.
